<script setup lang="ts">
import type { Component } from 'vue';
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  AtSign,
  BarChart3,
  BookMarked,
  BookOpen,
  Bot,
  Camera,
  CalendarDays,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  CirclePlus,
  CircleUserRound,
  CloudSun,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudSnow,
  Code2,
  Disc3,
  Droplets,
  Coffee,
  ExternalLink,
  FileDown,
  Gamepad2,
  Globe,
  GitBranch,
  GripVertical,
  Headphones,
  Home,
  ImageOff,
  Keyboard,
  Library,
  Link2,
  LayoutGrid,
  ListOrdered,
  ListMusic,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessagesSquare,
  Mic,
  Monitor,
  Music2,
  Palette,
  Pause,
  Pencil,
  Play,
  Plus,
  RefreshCcw,
  Radio,
  Repeat1,
  Repeat2,
  Rss,
  Save,
  Search,
  Send,
  Settings2,
  Share2,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Star,
  Sun,
  Shuffle,
  SkipBack,
  SkipForward,
  Trash2,
  UserRound,
  Video,
  Volume2,
  VolumeX,
  Wind,
  X,
  ZoomIn,
  ZoomOut,
} from '@lucide/vue';
import type { IconName } from '../../data/types';

interface Props {
  /** 要显示的语义图标名称。 */
  name: IconName;
  /** 图标边长，单位为像素。 */
  size?: number;
  /** SVG 线条宽度。 */
  strokeWidth?: number;
}

const props = withDefaults(defineProps<Props>(), {
  size: 18,
  strokeWidth: 1.8,
});

/**
 * 将数据层的语义图标映射为 Lucide Vue 组件。
 */
const iconMap: Record<IconName, Component> = {
  activity: Activity,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUpDown: ArrowUpDown,
  at: AtSign,
  book: BookOpen,
  bookMarked: BookMarked,
  bot: Bot,
  brew: Coffee,
  calendar: CalendarDays,
  camera: Camera,
  chart: BarChart3,
  check: Check,
  chevronDown: ChevronDown,
  circlePlus: CirclePlus,
  circleUser: CircleUserRound,
  cloud: CloudSun,
  cloudFog: CloudFog,
  cloudLightning: CloudLightning,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  code2: Code2,
  disc3: Disc3,
  droplets: Droplets,
  external: ExternalLink,
  fileDown: FileDown,
  game: Gamepad2,
  globe: Globe,
  github: GitBranch,
  gripVertical: GripVertical,
  headphones: Headphones,
  home: Home,
  imageOff: ImageOff,
  keyboard: Keyboard,
  library: Library,
  link: Link2,
  layoutGrid: LayoutGrid,
  listOrdered: ListOrdered,
  listMusic: ListMusic,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  messageCircle: MessageCircle,
  messagesSquare: MessagesSquare,
  mic: Mic,
  monitor: Monitor,
  music: Music2,
  palette: Palette,
  pause: Pause,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  refresh: RefreshCcw,
  radio: Radio,
  report: ChartNoAxesCombined,
  repeatOne: Repeat1,
  repeat: Repeat2,
  rss: Rss,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings2,
  share: Share2,
  shoppingBag: ShoppingBag,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  shuffle: Shuffle,
  skipBack: SkipBack,
  skipForward: SkipForward,
  trash: Trash2,
  user: UserRound,
  video: Video,
  volume: Volume2,
  volumeX: VolumeX,
  wind: Wind,
  x: X,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
};
</script>

<template>
  <component
    :is="iconMap[props.name]"
    :size="props.size"
    :stroke-width="props.strokeWidth"
    aria-hidden="true"
  />
</template>
